list_words = {'ada';'ada';'aza';'aza';'aba';'aba';'ata';'ata';'ana';'ana';...
    'ama';'ama';'asa';'asa';'apa';'apa';'ava';'ava';'afa';'afa';'aga';...
    'aga';'aka';'aka'};

word_pairs_voicing = {{'aba','apa'},{'ada','ata'},{'ava','afa'},...
    {'aga','aka'},{'aza','asa'}};

word_pairs_place = {{'apa','ata'},{'aba','aga'},{'ava','aza'},...
    {'afa','asa'},{'ama','ana'}};

word_pairs_manner = {{'ada','aza'},{'aza','ana'},{'aba','ama'}...
    {'ada','ana'},{'ata','asa'}};
