constructCategoryTrainingStimulus(trainingStimuli{1}(:,1));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,2));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,3));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,4));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,5));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,6));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,7));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,8));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,9));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,10));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,11));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,12));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,13));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,14));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,15));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,16));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,17));
waitSecs(1)
constructCategoryTrainingStimulus(trainingStimuli{1}(:,18));