% 
% list_words = {'ada';'aza';'aba';'ata';'ana';...
%     'ama';'asa';'apa';'ava';'afa';'aga';...
%     'aka'};
% 

list_words = {'cuff';'cub';'cup';'cuss';'suck';'puck';'pug';'buck';'bug';'pun';...
    'bun';'sun';'fun';'pus';'sub';'sup';'pub';'pup';'puff';'bus';'buff';...
    'buzz';'sud';'putt';'but';'bop';'pop';'sop'};
% word_pairs_voicing = {{'aba','apa'},{'ada','ata'},{'ava','afa'},...
%     {'aga','aka'},{'aza','asa'}};
% 
% word_pairs_place = {{'apa','ata'},{'aba','aga'},{'ava','aza'},...
%     {'afa','asa'},{'ama','ana'}};
% 
% word_pairs_manner = {{'ada','aza'},{'aza','ana'},{'aba','ama'}...
%     {'ada','ana'},{'ata','asa'}};

% word_pairs = {{'apa','ata'},{'aba','aga'},{'ava','aza'},...
%      {'afa','asa'},{'ama','ana'}};

% word_paris = {{'cup','cub'},{'pug','bug'},{'pug','puck'},{'puck','pug'},{'bug','pug'},{'bug','buck'},{'bun','pun'},{'pun','bun'},{'pup','pub'},{'sup','sub'},{'sub','sup'},{'but','bud'},{'buzz','bus'},{'cuss','cuz'},{'bus','buzz'}, ... 
%     {'cuss','cut'},{'buzz','bud'},{'bug','mug'},{'sub','sum'},{'bus','bum'},{'suck','tuck'},{'pus','putt'},{'sub','tub'},{'bus','but'},{'but','bus'},{'sop','top'},{'bun','bud'},{'sud','sun'},{'buzz','bun'},{'bun','buzz'},{'buck','muck'},{'buff','muff'},{'bop','mop'},{'but','mut'}, ... 
%     {'cup','cut'},{'cuss','cuff'},{'cuff','cuss'},{'bun','bum'},{'sun','sum'},{'pop','pot'},{'bop','bot'},{'putt','pup'},{'bug','bub'},{'bun','gun'},{'pub','pug'},{'but','gut'},{'bus','buff'},{'buff','bus'}};

word_pairs_voicing = {{'cup','cub'},{'pug','bug'},{'pug','puck'},{'puck','pug'},{'bug','pug'},{'bug','buck'},{'bun','pun'},{'pun','bun'},{'pup','pub'},{'sup','sub'},{'sub','sup'},{'but','bud'},{'buzz','bus'},{'cuss','cuz'},{'bus','buzz'}};

word_pairs_manner = {{'cuss','cut'},{'buzz','bud'},{'bug','mug'},{'sub','sum'},{'bus','bum'},{'suck','tuck'},{'pus','putt'},{'sub','tub'},{'bus','but'},{'but','bus'},{'sop','top'},{'bun','bud'},{'sud','sun'},{'buzz','bun'},{'bun','buzz'},{'buck','muck'},{'buff','muff'},{'bop','mop'},{'but','mut'}};

word_pairs_place = {{'cup','cut'},{'cuss','cuff'},{'cuff','cuss'},{'bun','bum'},{'sun','sum'},{'pop','pot'},{'bop','bot'},{'putt','pup'},{'bug','bub'},{'bun','gun'},{'pub','pug'},{'but','gut'},{'bus','buff'},{'buff','bus'}};